# 开发环境配置
spring:
  mail:
    from-address: 1519939545@qq.com
  datasource:
    url: jdbc:mysql://localhost:3306/student_assessment_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Ab*83327000
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  
  # redis:
  #   host: localhost
  #   port: 6379
  #   database: 0
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

# MyBatis（确保 dev 下也能解析 mapper 文件）
mybatis:
  mapper-locations: classpath*:mapper/*.xml

# 开发环境日志配置
logging:
  level:
    com.noncore.assessment: INFO
    root: WARN

# 开发环境文件上传配置
file:
  upload-dir: ./uploads
  max-size: 50MB
  
# 开发环境JWT配置
jwt:
  secret: dev-jwt-secret-key-for-development-environment-should-be-secure
  expiration: 86400000  # 24小时 

# 开发环境默认走 OpenRouter（OpenAI 兼容）。密钥请用环境变量 DEEPSEEK_API_KEY 注入。
ai:
  default-provider: openrouter
  providers:
    openrouter:
      base-url: https://openrouter.ai/api
      # api-key 走环境变量 OPENROUTER_API_KEY
    deepseek:
      base-url: https://api.deepseek.com
      # api-key 走环境变量 DEEPOFFICIAL_API_KEY
  deepseek:
    model: deepseek/deepseek-chat-v3-0324:free